# Site
name: "The ChadGPT"
title: "Tomorrow's AI"
description: "Welcome to The ChadGPT! I’m Shreyas, your guide to exploring AI’s coolest innovations. Here, we mix curiosity with fun, diving into the future of AI without the boring stuff. Let’s learn, laugh, and discover where AI is headed!"
logo: 'assets/images/fingerguns.png'
favicon: 'assets/images/yay-frog.gif'
baseurl: /
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Shreyas
    display_name: K
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: shreyashkathiriya@gmail.com
    web: https://aicraftersage.github.io/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Mediumish, a Bootstrap Medium styled template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  Shreyas:
    name: Shreyas
    display_name: K
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: shreyashkathiriya@gmail.com
    web: https://aicraftersage.github.io/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
